name: fit_start
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  page_transition: ^2.2.1
  lottie: ^3.3.1
  flutter_screenutil: ^5.9.3
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  get_storage: ^2.1.1
  form_validator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.png
    - assets/images/ic_launcher.png
    - assets/animations/animation.json
    - assets/animations/female.json
    - assets/animations/male.json
    - assets/animations/login.json
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21
